name: Generate contribution animation

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate light and dark contribution animations
        uses: Platane/snk@v3
        with:
          github_user_name: mtariqi
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%230F766E&color_dots=%23EBEDF0,%2399F6E4,%235EEAD4,%2314B8A6,%230F766E
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%235EEAD4

      - name: Publish animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
